'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Icons
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FurryArtStudio.Icons", GetType(Icons).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property FormFileDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormFileDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property FormFileLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormFileLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property FormImageDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormImageDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property FormImageLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormImageLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property FurryArtStudio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FurryArtStudio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCloneDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCloneDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCloneLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCloneLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCloseDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCloseDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCloseLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCloseLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCopyDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCopyDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCopyLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCopyLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCopyToDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCopyToDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuCopyToLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuCopyToLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuDeleteDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuDeleteDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuDeleteLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuDeleteLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuDevToolsDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuDevToolsDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuDevToolsLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuDevToolsLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuEditDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuEditDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuEditLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuEditLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuEditLineDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuEditLineDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuEditLineLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuEditLineLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuExportCsvDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuExportCsvDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuExportCsvLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuExportCsvLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuExtractDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuExtractDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuExtractLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuExtractLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileInputDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileInputDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileInputLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileInputLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileNewDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileNewDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileNewLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileNewLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileOutputDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileOutputDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFileOutputLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFileOutputLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderCloseDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderCloseDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderCloseLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderCloseLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderDelDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderDelDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderDelLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderDelLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderEditDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderEditDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderEditLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderEditLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderInputDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderInputDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderInputLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderInputLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderNewDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderNewDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderNewLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderNewLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderOpenDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderOpenDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderOpenLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderOpenLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderOutputDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderOutputDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFolderOutputLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFolderOutputLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFoldersDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFoldersDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFoldersLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFoldersLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFullscreenDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFullscreenDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuFullscreenLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFullscreenLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuGithubDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuGithubDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuGithubLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuGithubLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuImagePlayDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuImagePlayDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuImagePlayLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuImagePlayLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuInfoDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuInfoDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuInfoLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuInfoLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuLeftDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuLeftDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuLeftLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuLeftLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuNextDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuNextDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuNextLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuNextLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPinDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPinDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPinLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPinLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPreviousDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPreviousDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPreviousLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPreviousLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPrintDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPrintDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPrintLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPrintLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPropertiesDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPropertiesDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuPropertiesLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuPropertiesLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuRefreshDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuRefreshDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuRefreshLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuRefreshLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuRightDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuRightDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuRightLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuRightLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSearchDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSearchDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSearchLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSearchLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSettingsDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSettingsDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSettingsLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSettingsLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuShieldDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuShieldDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuShieldLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuShieldLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuStarDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStarDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuStarLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStarLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSupportDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSupportDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuSupportLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuSupportLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuTerminalDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuTerminalDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuTerminalLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuTerminalLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuTutorialDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuTutorialDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuTutorialLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuTutorialLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuViewDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuViewDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuViewLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuViewLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuWallpaperDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuWallpaperDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuWallpaperLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuWallpaperLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuWebsiteDark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuWebsiteDark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property MenuWebsiteLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuWebsiteLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
