'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Licenses
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FurryArtStudio.Licenses", GetType(Licenses).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似     
        '''    FurryArtStudio 是一款轻量级、强大的本地工具，专为整理和管理兽设稿件、参考资料、OC 内容以及图像文档而设计。
        '''
        '''    核心优势
        '''    - 完全免费：FurryArtStudio 坚持完全免费更新。
        '''    - 离线运行：所有数据仅存储在您的本地设备上。
        '''    - 隐私优先：程序除检查更新外，不会联网、不会上传任何用户数据或稿件信息。
        '''    - 开源许可：Apache License 2.0（详见 LICENSE.txt）
        '''    - 当前平台：Windows（未来计划支持更多平台）
        '''
        '''    重要提醒
        '''    完全免费 &amp; 永久开源：
        '''    - FurryArtStudio 完全免费使用，不收取任何费用（包括订阅、解锁功能、VIP 等）。
        '''    - 我们致力于提供高质量的开源工具，让每位 Furry 创作者都能轻松管理自己的稿件和参考资料。
        '''    请务必从官方渠道下载：
        '''    - 唯一官方下载来源：GitHub 仓库 https://github.com/xionglongztz/FurryArtStudio
        '''    - 请勿从 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AboutText() As String
            Get
                Return ResourceManager.GetString("AboutText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似                                  Apache License
        '''                           Version 2.0, January 2004
        '''                        http://www.apache.org/licenses/
        '''
        '''   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        '''
        '''   1. Definitions.
        '''
        '''      &quot;License&quot; shall mean the terms and conditions for use, reproduction,
        '''      and distribution as defined by Sections 1 through 9 of this document.
        '''
        '''      &quot;Licensor&quot; shall mean the copyright owner or entity authorized by
        '''      the copyright owner that is [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property LicenseText() As String
            Get
                Return ResourceManager.GetString("LicenseText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''    FurryArtStudio 隐私政策
        '''
        '''    生效日期：2026年2月21日
        '''    最新更新日期：2026年2月21日
        '''
        '''    FurryArtStudio（以下简称&quot;本软件&quot;）是由个人开发者 雄龙ztz（GitHub: xionglongztz）开发并开源的本地稿件管理工具。我们高度重视您的隐私和数据安全。本隐私政策说明本软件如何处理您的信息。
        '''    
        '''    1. 我们不收集任何个人信息
        '''    本软件完全离线运行，所有稿件、图片、标签、标题、作者、角色信息、元数据等全部存储在您的本地设备上。我们不会：
        '''    收集、传输、存储或访问您的任何个人数据或稿件内容；
        '''    获取您的设备信息（如硬件ID、IP地址、操作系统版本等，除非您手动检查更新）；
        '''    进行任何形式的遥测；
        '''    将您的任何数据用于训练AI模型或其他目的；
        '''    与任何第三方共享您的信息。
        '''
        '''    2. 唯一的联网行为：检查更新
        '''    本软件仅在您手动或自动启用&quot;检查更新&quot;功能时，才会短暂联网连接官方源，仅下载版本信息和更新包。本软件本身不会上传任何用户数据或记录访问行为。 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property PrivacyText() As String
            Get
                Return ResourceManager.GetString("PrivacyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 
        '''    FurryArtStudio 用户协议
        '''
        '''    重要提醒：请仔细阅读以下内容
        '''    使用本软件即表示您已阅读、理解并同意本协议的所有条款。如果不同意，请立即停止使用。
        '''
        '''    1. 软件许可
        '''    本软件根据 Apache License 2.0 开源许可提供。您可以免费使用、修改、分发，但需遵守许可条款（详见项目根目录 LICENSE 文件）。
        '''
        '''    2. &quot;按现状&quot;提供，无任何保证
        '''    本软件按&quot;现状&quot;（AS IS）提供，不提供任何明示或暗示的保证，包括但不限于：
        '''    对适销性、特定用途适用性、非侵权性的任何保证；
        '''    软件无错误、无中断、无病毒或完全适合您的需求。
        '''    开发者不对因使用本软件导致的任何直接、间接、附带、特殊、惩戒性或后果性损害负责，包括但不限于数据丢失、业务中断、利润损失等。即使开发者已被告知此类损害的可能性，亦不承担责任。
        '''    
        '''    3. 数据备份与丢失责任
        '''    本软件仅为本地管理工具，不提供自动备份或数据恢复功能。
        '''    开发者强烈建议您定期备份所有稿件文件和数据库（例如复制整个库文件夹到外部存储） [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property TermsText() As String
            Get
                Return ResourceManager.GetString("TermsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property WhatsNewText() As String
            Get
                Return ResourceManager.GetString("WhatsNewText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
